language: python
os: linux
dist: bionic
python:
 - "3.8"
 - "3.9"
 - "3.10"
 - "3.11"
services:
 - postgresql
env:
 - DB="sqlite" SAURL="sqlite:///:memory:"
 - DB="postgres" SAURL="postgresql://postgres:postgres@localhost/skosprovider_sqlalchemy"
install:
 - pip install --upgrade pip setuptools importlib-metadata
 - pip install -r requirements-dev.txt
 - python setup.py -q develop
before_script:
 - "if [[ $DB = 'postgres' ]]; then psql -U postgres -c 'create database skosprovider_sqlalchemy'; fi"
script: 
 - py.test --sqlalchemy_url $SAURL -v --cov skosprovider_sqlalchemy
after_success: coveralls
